title: Chris Buckley
description: Netlify plugin for post-build SEO linting

url: https://cmbuckley.co.uk
baseurl: /netlify-plugin-seo-lint

repository: cmbuckley/netlify-plugin-seo-lint
remote_theme: "cmbuckley/cmbuckley.github.io"

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

exclude:
  - Gemfile
  - vendor
  - node_modules

markdown: kramdown
highlighter: rouge
